using Data.Interfaces;

namespace Business.Resources;
//Simple class to generate new project numbers, based on the latest project number in the database. Generated by ChatGPT4o
public static class ProjectNumberGenerator
{
    public static async Task<string> GenerateAsync(IProjectRepository projectRepository)
    {
        // Fetch the latest project number
        var latestProject = await projectRepository.GetLatestProjectAsync();

        if (latestProject is null || string.IsNullOrWhiteSpace(latestProject.ProjectNumber))
            return "P-1001"; // Default starting point

        // Extract number part and increment
        var lastNumber = int.Parse(latestProject.ProjectNumber.Split('-')[1]);
        return $"P-{lastNumber + 1}";
    }
}

